os:
  - linux

language: node_js
node_js:
  - '12'

cache:
  directories:
    - node_modules

stages:
  - test
  - pack
  - name: deploy
    if: (type = push) AND branch =~ ^(master|v\d+\.\d+)$

jobs:
  include:
    - stage: test
      script:
        - echo $TRAVIS_OS_NAME
        - node --version
        - npm --version
        - echo "Testing Started ..."
        - npm test
        - echo "Testing Finished."

    - stage: pack
      script:
        - ./scripts/generate-version.sh
        - npm run test:pack && echo 'NPM Pack Testing Passed.'

    - stage: deploy
      script:
        - echo "Deploying to NPM ..."
        - npm version
        - ./scripts/generate-version.sh
        - ./scripts/package-publish-config-tag.sh
        - npm run dist

      deploy:
        provider: npm
        email: zixia@zixia.net
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          all_branches: true

notifications:
  email:
    on_success: change
    on_failure: change
